"""Prevent deletion of applications on job delete

Revision ID: 3fd8ce382088
Revises: 3bf8e49f3f10
Create Date: 2026-05-11 12:13:47.864762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd8ce382088'
down_revision: Union[str, Sequence[str], None] = '3bf8e49f3f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_job_applications_job_id_jobs'), 'jobs', ['job_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_memberships_name'), ['name'])

    with op.batch_alter_table('user_memberships', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_memberships_user_id'), ['user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_memberships', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_memberships_user_id'), type_='unique')

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_memberships_name'), type_='unique')

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        # batch_op.drop_constraint(batch_op.f('fk_job_applications_job_id_jobs'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['id'])

    # ### end Alembic commands ###
