"""add verification and created_at fields

Revision ID: 8b3201b67b8f
Revises: af34d69c54bf
Create Date: 2026-06-16 16:36:42.479194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3201b67b8f'
down_revision: Union[str, Sequence[str], None] = 'af34d69c54bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('verification_reason', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_reason')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
