"""add_membership_fields

Revision ID: af34d69c54bf
Revises: 8c26d5e7033b
Create Date: 2026-06-09 10:51:04.731524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af34d69c54bf'
down_revision: Union[str, Sequence[str], None] = '8c26d5e7033b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('highlight', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_column('highlight')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
